### ISSUE TITLE
Not seeing charts

### ISSUE THREAD

**Issue by orenyomtov** [mirthestam/lean-monitor#11]
Hey,

Thanks for creating this project, it's exactly what I was looking for in order to execute offline backtests using Lean.

I have just tried it, and I get 5 different panes, though none of them include charts:
![image](https://cloud.githubusercontent.com/assets/168856/25999304/43cbddb6-372d-11e7-98cb-bb53af054096.png)

**Comment by mirthestam** [comment]
Hi Oren. The panels shown are 'tool panels' When charts are received, the tabs should show in the center. Can you 'export' the data and check whether chart data is present? This should be a 'charts' element in the generated JSON file.

**Comment by mirthestam** [comment]
Any updates?
