### ISSUE TITLE
[FR] Use Avalonia for UI

### ISSUE THREAD

**Issue by laur89** [mirthestam/lean-monitor#16]
Would you consider using cross-platform [Avalonia](https://github.com/AvaloniaUI/Avalonia/) instead of WPF?
Would be beneficial with cross-compatibility in mind.

**Comment by mirthestam** [comment]
I really like the concept of Avalonia. However, it is not that simple to replace WPF. For example there is no Avalonia implementation for LiveCharts. Second, I use a lot of custom theming for the UI that needs to be redesigned. Personally I've decided to use a virtual machine to run the desktop monitor. However, I welcome any effort to port the monitor to Avalonia.

**Comment by laur89** [comment]
Cool, I'm only superficially familiar with C# UI and wasn't aware the feature mis-parity.
So in your setup you run lean-monitor off a vm and connect it to running Lean instance?
